export const FORM_NEW_RECIPE__ADD_INGREDIENT =
  'FORM_NEW_RECIPE__INGREDIENT_ADD';

export const FORM_NEW_RECIPE__INGREDIENT_PLUS =
  'FORM_NEW_RECIPE__INGREDIENT_PLUS';
export const FORM_NEW_RECIPE__INGREDIENT_MINUS =
  'FORM_NEW_RECIPE__INGREDIENT_MINUS';
export const FORM_NEW_RECIPE__INGREDIENT_REMOVE =
  'FORM_NEW_RECIPE__INGREDIENT_REMOVE';

export const FORM_NEW_RECIPE__CLEAR_FORM = 'FORM_NEW_RECIPE__CLEAR_FORM';
