export const INGREDIENT_LIST__ADD = 'INGREDIENT_LIST__ADD';
export const INGREDIENT_LIST__REMOVE = 'INGREDIENT_LIST__REMOVE';
export const INGREDIENT_LIST__PLUS = 'INGREDIENT_LIST__PLUS';
export const INGREDIENT_LIST__MINUS = 'INGREDIENT_LIST__MINUS';
export const INGREDIENT_LIST__UPDATE = 'INGREDIENT_LIST__UPDATE';
