export const CRAFTING_TABLE__ADD_RECIPE = 'CRAFTING_TABLE__ADD_RECIPE';

export const CRAFTING_TABLE__INIT_RECIPE_LIST =
  'CRAFTING_TABLE__INIT_RECIPE_LIST';

export const CRAFTING_TABLE__ADD_INGREDIENT = 'CRAFTING_TABLE__ADD_INGREDIENT';

export const CRAFTING_TABLE__CLEAR_FORM = 'CRAFTING_TABLE__CLEAR_FORM';
